### PR TITLE
Fix spelling mistakes in descriptions

### PR DESCRIPTION
**Pull request by andrewgarner**

### CODE REVIEW

**Comment by cbaines** [comment]
:+1:

**Comment by binaryberry** [comment]
Tests are failing - you need to run [rake](https://github.com/alphagov/govuk-content-schemas#rakefile) to rebuild the schemas and propagate the changes.

**Comment by binaryberry** [comment]
We try to avoid having merge commits in the history and rebase against master and force push instead, to keep a cleaner history. I admit I can't find this rule in written form, we should probably add it to the git styleguide...

**Comment by andrewgarner** [comment]
I pushed up the merge and fixup commits to avoid having to force push the branch whilst it's under development/review. I'll rebase before merging if the changes are approved.

**Comment by binaryberry** [comment]
Ok, fine by me then!

**Pull request merged**
