### PR TITLE
Add publisher examples

### PR DESCRIPTION
**Pull request by steventux**
https://trello.com/c/R46p9TMH/366-docs-publisher-examples-for-publishing-api

Publisher examples for different content formats for both content and links where applicable.

### CODE REVIEW

**Comment by danielroseman** [comment]
I don't think the links ones are right: they should literally just have the `links` hash.

**Comment by steventux** [comment]
As discussed, the links hash isn't valid on its own, I'll look for a way to validate the /v2 links payload separate from the content payload.

**Comment by elliotcm** [comment]
@danielroseman are you happy with this?

**Comment by danielroseman** [comment]
Steve and I have been working on this today, more changes coming.

**Pull request closed without merging**
