### PR TITLE
Update contact headings

### PR DESCRIPTION
**Pull request by chris-gds**
## What?

Updating schemas to reflect work done on this PR https://github.com/alphagov/govspeak/pull/206

## Why?

Headings have been changed to paragraph copy within contact information due to a11y.  They shouldn't be bold as it looks like a heading but is not also the h3 is not always correct when used in the flow of a document

## Anything else?
Live Ref page
https://www.gov.uk/government/news/new-voluntary-calorie-guidelines-to-help-industry-tackle-obesity

image

image

### CODE REVIEW

**Review by alex-ju — APPROVED** [review]
Updating these examples makes sense after updating `govspeak` to replace the heading with a paragraph.

However, I think there is a tradeoff with [the change itself](https://github.com/alphagov/govspeak/pull/206). I understand there were problems with the heading level, but with this change, people will find it harder to reach the contact details using the landmark navigation.

**Comment by chris-gds** [comment]
> However, I think there is a tradeoff with [the change itself](https://github.com/alphagov/govspeak/pull/206). I understand there were problems with the heading level, but with this change, people will find it harder to reach the contact details using the landmark navigation.

🤔  I take your point, ideally this entire contact section needs _something_ so a user can easily navigate to it.  First thoughts thinking `<section>` & `<address>` would aid with this. Will revisit.

**Comment by alex-ju** [comment]
> > However, I think there is a tradeoff with [the change itself](https://github.com/alphagov/govspeak/pull/206). I understand there were problems with the heading level, but with this change, people will find it harder to reach the contact details using the landmark navigation.
> 
> 🤔 I take your point, ideally this entire contact section needs _something_ so a user can easily navigate to it. First thoughts are thinking `<section>` & `<address>` would aid with this. Will revisit.

Indeed, the contact section could be improved with semantic markup and microdata, but I'm not sure if it's in the scope of this work.

**Comment by chris-gds** [comment]
Captured suggestions for prioritisation by PM

**Pull request merged**
