### PR TITLE
Revert "Remove unused tags from detailed guide details"

### PR DESCRIPTION
**Pull request by tijmenb**
Reverts alphagov/govuk-content-schemas#291.

The `details.tags` is used for email-alerts:

https://github.com/alphagov/whitehall/blob/39f8a6342f449f9a0f01701afce61212cac97e47/app/presenters/publishing_api_presenters/edition.rb#L63-L74

### CODE REVIEW

**Comment by fofr** [comment]
:/

Do we intend to switch email-alerts away from this?

**Comment by tijmenb** [comment]
Yeah, that's the intention. I'm not sure what's involved in that though. I'll put in into the email backlog.

**Comment by tvararu** [comment]
Merging to get https://github.com/alphagov/whitehall/pull/2553 to pass.

**Comment by fofr** [comment]
Has there been any progress on this since April?

**Pull request merged**
