### PR TITLE
Gitignore *.json.publisher_v2.valid files

### PR DESCRIPTION
**Pull request by issyl0**
- These seem to be a new addition. We couldn't work out why they were
  polluting our `git status` when we were generating new schemas and why
  we'd never seen anything like them before, then we found this file and
  determined they'd been missed when they were added.

### CODE REVIEW

**Comment by jamiecobbett** [comment]
I suspect its a result of https://github.com/alphagov/govuk-content-schemas/pull/164

**Comment by jamiecobbett** [comment]
Seems good to merge to me, @danielroseman?

**Comment by danielroseman** [comment]
:+1: but needs rebasing.

**Comment by davidbasalla** [comment]
Rebased!

**Comment by issyl0** [comment]
Thanks @davidbasalla for the rebase! :star:

**Pull request merged**
