### PR TITLE
Update specialist frontend schemas to what is on live

### PR DESCRIPTION
**Pull request by mcgoooo**
this updates the content schemas to what is on live

this is needed before we start the template consolidation work

### CODE REVIEW

**Comment by nickcolley** [comment]
Nit: Can you squash the last commit, since it's removing something you didn't want to add?

Also be good to rewrite 'forntend' to 'frontend' 👼

**Comment by fofr** [comment]
Here's out style guide for git commits:
https://github.com/alphagov/styleguides/blob/master/git.md#commit-messages

Your commits say _what_ but not _why_, could you add something about why you're making these changes?

The commit summary should be:
> Capitalised, short (50 chars or less) summary

Can the commits refer to _examples_, as you haven't updated the schema.

**Comment by tijmenb** [comment]
@mcgoooo can you rebase this?

**Comment by mcgoooo** [comment]
closing this as i dont the bease and then the reword, git went haywaire

**Pull request closed without merging**
