### PR TITLE
Tidy up schemas

### PR DESCRIPTION
**Pull request by h-lame**
Best reviewed as single commits, but the tl;dr is:

1. Remove `xxx_name` fields from specialist documents as these are only ever sent to rummager, never to publishing-api.
2. Fix the pattern used to match "date" fields to disallow a value of `00` in the `dd` part of `yyyy-mm-dd`

### CODE REVIEW

**Comment by elliotcm** [comment]
👍 You'll probably want another commit after running `rake`.

**Comment by elliotcm** [comment]
Correction, you've already run that.  Could you pull the `dist/*` changes into separate commits?

**Comment by h-lame** [comment]
Sure.  Incoming in 5... 4...

**Comment by h-lame** [comment]
@elliotcm done all the dist changes as one commit, that ok?

**Comment by elliotcm** [comment]
Marvellous.

**Pull request merged**
