### PR TITLE
Add govspeak content-type to all fields within details hash

### PR DESCRIPTION
**Pull request by mathildathompson**
- All fields in financial_releases_campaign details hash now store govspeak and html.
  - Publishing_app can pull govspeak content for editing. Frontend_app can render html.
  - I have tidied up the financial_releases_campaign frontend examples to contain data of relevant length.

### CODE REVIEW

**Comment by boffbowsh** [comment]
Can the `description` not co-exist with the `$ref`s?

**Comment by mathildathompson** [comment]
@boffbowsh I could not get it to no.....

**Comment by boffbowsh** [comment]
Fair enough :)

**Comment by tijmenb** [comment]
https://github.com/alphagov/govuk-content-schemas/commit/fddb748b555631f2a0f86634deb616283231962e does have `description` & `$ref` in the definition. What error were you seeing?

**Pull request merged**
