### PR TITLE
Add legend field to campaign page

### PR DESCRIPTION
**Pull request by mathildathompson**

### CODE REVIEW

**Comment by tombooth** [comment]
Hi @mathildathompson can you rebase this PR?

**Comment by mathildathompson** [comment]
@tombooth done :-)

**Comment by tombooth** [comment]
Just for reference you can see the text in place in the Lloyds campaign page (it's bordered in red).

legend-campaign

**Comment by mathildathompson** [comment]
Great thanks!

On Thu, Jan 14, 2016 at 11:42 AM, Tom Booth <notifications@github.com>
wrote:

> Merged #193 <https://github.com/alphagov/govuk-content-schemas/pull/193>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/alphagov/govuk-content-schemas/pull/193#event-514873199>
> .
>



-- 
--------------------------
Mathilda Thompson
07867986492

**Pull request merged**
