### PR TITLE
Add examples of person frontend schemas

### PR DESCRIPTION
**Pull request by sihugh**
Includes a simple example and one with multiple roles/former roles.

### CODE REVIEW

**Comment by barrucadu** [comment]
@sihugh Is this PR still useful?

**Comment by sihugh** [comment]
It's possibly out of date because of the work that @thomasleese is doing. Happy to close if he doesn't feel it's needed

**Comment by thomasleese** [comment]
It is out of date, I keep meaning to update it, but haven't got round to it yet. Feel free to close it and I can re-open it later. :)

**Comment by sihugh** [comment]
☝️

**Pull request closed without merging**
