### PR TITLE
HTML publication schema and example additions

### PR DESCRIPTION
**Pull request by benlovell**
Trello: https://trello.com/c/Wcl1hWJ2

Adds further required examples and schema alterations for HTML publications.

This is good for commentary thus far, but needs some attention around the rendering of fractional images.

### CODE REVIEW

**Comment by fofr** [comment]
@benlovell Will you be adding the budget example? ie automatically numbered.

**Comment by benlovell** [comment]
@fofr 👍

**Comment by benlovell** [comment]
@fofr 30e002d adds the 2015 budget example.

**Comment by boffbowsh** [comment]
Looks like this needs a force-push to retrigger the tests

**Comment by benlovell** [comment]
@dsingleton The fraction paths are updated now. Could you please review?

**Comment by dsingleton** [comment]
The examples have the web host, `https://www.gov.uk/government/assets/fractions/1_4-b6128849c8da3b46b9cb5a6918cfe084.png` - should that be `https://assets.digital.cabinet-office.gov.uk/government/assets/fractions/1_4-b6128849c8da3b46b9cb5a6918cfe084.png` (I think thats what we do elsewhere)

**Comment by boffbowsh** [comment]
What @dsingleton said

**Comment by benlovell** [comment]
@dsingleton @boffbowsh Rebased in.

**Comment by dsingleton** [comment]
:+1: from me, and it renders well in the FE branch.

**Pull request merged**
