### PR TITLE
Reformat examples as part of the build

### PR DESCRIPTION
**Pull request by tijmenb**
This adds a step to the build process to reformat the example JSON files. The main reason is that this allows us to quickly edit all the examples. For example, #444 removes the `format` field simply by adding `data.delete("format")` to the rake task.

This will also prevent errors with duplicated keys in the JSON (converting it to a Ruby hash will solve them).

PR prompted by https://github.com/alphagov/govuk-content-schemas/pull/444#discussion_r90045687.

cc @andrewgarner

### CODE REVIEW

**Comment by andrewgarner** [comment]
👍 

After my comment yesterday I was also thinking about whether we could incorporate something like https://github.com/PagerDuty/jsonlint

**Comment by tijmenb** [comment]
With this I think we catch most errors. The examples are validated against the schemas, so any syntax errors are picked up already.

**Comment by fofr** [comment]
:100: 👍

**Comment by fofr** [comment]
Can something similar be applied to `details.json` and `links.json`?

A PR made it through today that has incorrect indentation which I think this would have prevented:
https://github.com/alphagov/govuk-content-schemas/pull/447#pullrequestreview-10723190

**Comment by tijmenb** [comment]
Sure, I don't see any reason not to do that. Seems useful!

**Pull request merged**
