### PR TITLE
Reinstates "Updating specialist document formats for North Macedonia"

### PR DESCRIPTION
**Pull request by Tetrino**
Country name changed a couple years ago but we had some leftovers in
some document types.

This reverts commit c96d031485f2b3643bb99969bdcf68dc1fe70fc0.

### CODE REVIEW

**Comment by Tetrino** [comment]
Having to close this due to jenkins jobs apparently not reporting??

**Comment by Tetrino** [comment]
Excuse the close/open spam, trying to get Jenkins to trigger the jobs again.

**Comment by benthorner** [comment]
I think we're just missing one update to [an example](https://github.com/alphagov/govuk-content-schemas/blob/532a0868f1cf86c96b3a090d1c73e67716dd0a57/examples/specialist_document/frontend/export-health-certificates.json#L854). Would you like to add that @Tetrino ? (Hopefully it will trigger an actual build in our _probably working now_ CI environment.)

**Comment by Tetrino** [comment]
@benthorner Sorry for the delay, and for missing the example in the reverting-revert. Just pushed it up

**Comment by benthorner** [comment]
Thanks @Tetrino! I've had some time to work on this while you've been away, and I think we should take a slightly different approach. I've raised a PR for this part of it: https://github.com/alphagov/govuk-content-schemas/pull/1014.

**Pull request closed without merging**
