### PR TITLE
Add document collections to detailed guides, add examples of more features

### PR DESCRIPTION
**Pull request by fofr**
* Add related guide to examples, to build frontend against
* Add document collections to detailed guide schema, and include examples
* Add examples of related mainstream content, document collections and related guides

Examples used:
https://www.gov.uk/guidance/onshore-wind-part-of-the-uks-energy-mix
https://www.gov.uk/guidance/living-in-fiji
https://www.gov.uk/guidance/living-in-fiji--2

Part of:
https://trello.com/c/k6H9gNKF/316-6-detailed-guides-migration-front-end-work-small

cc @mgrassotti @tvararu

### CODE REVIEW

**Comment by fofr** [comment]
Test failures appear unrelated?

**Comment by tvararu** [comment]
Yeah, test failures do appear to be unrelated.

Looks good. 👍

**Comment by boffbowsh** [comment]
This copies a pattern from Case Studies, but that pattern isn't valid. Updates to the underlying document collection won't update the "Part of" metadata of the Case Study or Detailed guide.

**Comment by boffbowsh** [comment]
This PR is going to bring Detailed guides document collections into line with Case studies, then we'll fix both in another PR.

**Pull request merged**
