### PR TITLE
    Add public_updated_at as an optional property

### PR DESCRIPTION
**Pull request by AndrewVos**
Adds to:

- redirect
- gone
- unpublishing
- coming_soon

This allows us to publish content, when that content has not been
published before, but has an "update_type" of "major".

### CODE REVIEW

**Comment by tuzz** [comment]
I think this may only be the case if there hasn't previously been a public_updated_at set via the put_content action. You can provide it either at update time or publish time, but one of those must be provided.

Either way, publishing api shouldn't be responding with a 500. We'll discuss this in the team next week.

**Comment by AndrewVos** [comment]
Thanks @tuzz. For now we've just used "major" (https://github.com/alphagov/service-manual-publisher/pull/170) temporarily. Though I'm not sure about why we original decided to even go with "minor". If publishing-api should accept the first put_content with "minor" then this pull request should be closed?

**Comment by boffbowsh** [comment]
This needs rebasing

**Comment by tijmenb** [comment]
:+1:

**Pull request merged**
